<?php

namespace OP\TradeBundle\Repository;

/**
 * testeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class testeRepository extends \Doctrine\ORM\EntityRepository
{
}
